// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BHI_oWowcJfU_qD0vUjr78FU4MpGMfA',
    appId: '1:196175023672:web:c428dc2abd64c3bdbd20cd',
    messagingSenderId: '196175023672',
    projectId: 'krusty-konnect-app',
    authDomain: 'krusty-konnect-app.firebaseapp.com',
    storageBucket: 'krusty-konnect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-qNyWw1dxde19UPPZ-ul-OzGRB8eg_E',
    appId: '1:196175023672:android:5ed542b11d260305bd20cd',
    messagingSenderId: '196175023672',
    projectId: 'krusty-konnect-app',
    storageBucket: 'krusty-konnect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmJetThw7nz0agW7OYLOSKaEFQD-cxh_A',
    appId: '1:196175023672:ios:b39b61ce79dce0eebd20cd',
    messagingSenderId: '196175023672',
    projectId: 'krusty-konnect-app',
    storageBucket: 'krusty-konnect-app.firebasestorage.app',
    iosBundleId: 'com.example.krustyKonnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmJetThw7nz0agW7OYLOSKaEFQD-cxh_A',
    appId: '1:196175023672:ios:b39b61ce79dce0eebd20cd',
    messagingSenderId: '196175023672',
    projectId: 'krusty-konnect-app',
    storageBucket: 'krusty-konnect-app.firebasestorage.app',
    iosBundleId: 'com.example.krustyKonnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0BHI_oWowcJfU_qD0vUjr78FU4MpGMfA',
    appId: '1:196175023672:web:e10a1eb08168516cbd20cd',
    messagingSenderId: '196175023672',
    projectId: 'krusty-konnect-app',
    authDomain: 'krusty-konnect-app.firebaseapp.com',
    storageBucket: 'krusty-konnect-app.firebasestorage.app',
  );

}